name: Build Mod

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

<<<<<<< HEAD
    - - name: Give gradlew permission
  run: chmod +x ./gradlew

- name: Build
  run: ./gradlew build

=======
      - name: Give gradlew permission
        run: chmod +x ./gradlew
>>>>>>> f2423a9671042998fae3960598aa1e774e4398de

      - name: Build
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: warden-shield-mod
          path: build/libs/warden-shield-mod-1.0.0.jar
